### ISSUE TITLE
How to use this frame in development environment?

### ISSUE THREAD

**Issue by zedde** [satsukita-andon/andon-frontend#5]
Dear @amutake 
👍  job frame.

>
how to use this frame in development environment like react-redux-universal-hot-example?

Thanks.

**Comment by amutake** [comment]
Sorry, what do you mean by that?
This repository is the implementation of https://new.satsukita-andon.com and not a react/redux example like react-redux-universal-hot-example.

**Comment by zedde** [comment]
I expression is not clear.
In fact, I like this simple framework to achieve `npm` and `bower`.
How to run in development environment. like use `npm run dev` ?

**Comment by zedde** [comment]
@amutake

**Comment by amutake** [comment]
Ah, I see. 
This does not have development environment starting command...
In production and development environment, I run `npm run start`.

**Comment by zedde** [comment]
:-) 
Thanks.

**Comment by amutake** [comment]
👍
